### PR TITLE
Simple GTK GUI demo displaying War and Peace.

### PR DESCRIPTION
**Pull request by Britefury**

### CODE REVIEW

**Comment by ltratt** [comment]
Hmm, gtk doesn't currently build on my machine (which obviously isn't anything to do with your PR, but it makes it hard for me to test!). I'm looking into this.

**Comment by Britefury** [comment]
Ready for review and merge.
Will take existing demo and refactor to start work on element tree.

**Comment by ltratt** [comment]
I have a few thoughts, in no particular order.

1) I think we should treat this as a demo, not as the "main" program of the library. Does Cargo have any notion of examples / demos directory[s]?

2) I was a bit surprised by the complexity of the program in using the API. Maybe my expectations are wrong? Or maybe there's a simpler API lurking within?

3) There are a few random blank lines lurking around.

**Comment by ltratt** [comment]
I forgot another. Oops!

4) The renderer appears to be called even when there's no rendering to do?

**Comment by Britefury** [comment]
To answer your queries:

1) I like the sound of this and will look into it
2) The version up there is very early development. My next set of commits that will end up in this branch will refactor the API to something simpler.
3) Most likely; will clean up soon.
4) If you are referring to the console messages, I guess its because GTK+ is sending draw calls for some reason. It may be just because it thinks it needs to refresh the area under the pointer or something - no idea why - the rectangle that GTK passes that describes the area to draw may be very small and this could be used as an optimisation in a future refactor.

**Comment by ltratt** [comment]
OK.

**Comment by Britefury** [comment]
The W&P demo has now been moved into the examples folder.
The API has been somewhat refactored. Elements are not constructed directly; you use the `lspace.pres` API to construct presentation objects -- essentially element factories -- that do the work of building elements for you.
The code that manages the GTK drawing area has been moved into its own module.
The W&P demo is now much smaller.

**Comment by ltratt** [comment]
[There are also still lots of extra newlines lurking around. I know they're a trivial thing, but it's worth killing as many before review as possible.]

**Comment by ltratt** [comment]
The API does now look usefully simpler. I think we're getting to the point where it's worth sitting down and thinking about how to render something Eco-like in this, and then think about what can be improved and simplified further.

**Comment by Britefury** [comment]
Python program gone; functionality rolled into w&p example, although it still calls Python to download the text file.
Blank lines and commented code are gone.

**Comment by ltratt** [comment]
Out of curiosity, is the Python code really necessary? Would something like https://github.com/hyperium/hyper do a better job? [There are probably other useful crates at http://crates.io/]

**Comment by Britefury** [comment]
Hyper now used instead of Python.

**Comment by ltratt** [comment]
Cool!

Can the Cargo file be made so that only the W&P example uses hyper, not the whole library? [I assume this is possible, but I admit, I don't know how... If not, it might suggest that the examples should have a separate Cargo.toml file?]

**Comment by Britefury** [comment]
Done.

**Comment by ltratt** [comment]
OK, I can't immediately test this on my system (until rust-gtk is updated...), but I think it's probably OK for merging. I think some squashing needs to go on, but I leave it upto you as to which need to be squashed and which don't. [You don't need to squash everything down into 1, necessarily.]

**Comment by Britefury** [comment]
Squashed.

**Comment by ltratt** [comment]
OK, thanks.

**Pull request merged**
