### PR TITLE
Basic text styling including Rust source code rendering example

### PR DESCRIPTION
**Pull request by Britefury**
Basic Rust source code rendering example with monospaced font and coloured text.

### CODE REVIEW

**Comment by ltratt** [comment]
One dumb question: do colours need to be represented as there f64s? Couldn't it be 3 i8s or something? [Or 4, if you want an alpha channel.]

**Comment by Britefury** [comment]
Good point. Generally I would prefer floats to ints; I find the range 0-1 (or 0%-100%) easier to think about.
I will change it t 4 `f32`s; that will give more compactness and allow the use of alpha.

**Comment by ltratt** [comment]
I think it would be better to use the standard integers here. If nothing else, 4 \* i8 will save a decent amount of memory vs. 4 \* f32s!

**Comment by Britefury** [comment]
Cairo accepts colours as floats, as do most vector graphics systems, so we are sticking with the more modern standard here. We also don't store colours very often; even for a rust file the size of War and Peace the current example would only store 3 colours as those 3 are references wherever they are needed.

`i8` colours are old-school and don't have many advantages IMHO. This is particularly apparent if you want to do any arithmetic with them, which can happen.

Come to think of it, I think it would be helpful for me to define a colour class in the math library. I will just go implement that...

**Comment by ltratt** [comment]
OK.

**Comment by ptersilie** [comment]
How do I run this? I tried
`cargo run --release --example w_and_p`
but only get a grey window.

**Comment by Britefury** [comment]
`cargo run --release --example render_rust`
(pardon me for not putting that in)

**Comment by Britefury** [comment]
Travis CI build error is due to Cairo compilation error; nothing to do with me..... :)

**Pull request merged**
