### PR TITLE
Hvf layouts

### PR DESCRIPTION
**Pull request by Britefury**
Implementation of horizontal, vertical and flow layouts with tests and benchmarks.

### CODE REVIEW

**Comment by ltratt** [comment]
This all looks reasonable to me. Is this ready for merging?

**Comment by Britefury** [comment]
Should be; please feel free :)

**Comment by ltratt** [comment]
OK, I think we should squash the two commits down?

**Comment by Britefury** [comment]
Done. Ready for merge.

**Comment by ltratt** [comment]
Good stuff!

**Pull request merged**
