### PR TITLE
New element reference type.

### PR DESCRIPTION
**Pull request by Britefury**
The `ElementRef` structure is used to represent references to elements.

### CODE REVIEW

**Comment by ltratt** [comment]
I might be a little dense here, but what's the point of the new indirection?

**Comment by Britefury** [comment]
Its slightly easier to write and is mainly there to support future development that will happen soon.

**Comment by ltratt** [comment]
Could you give a hint of the future developments? That would make the PR make a lot more sense (since adding the indirection clearly makes things more complex in the short term!).

**Comment by Britefury** [comment]
Okay, I've decided to back this change out. I've modified the change further down the line so that it does not require it.

**Comment by ltratt** [comment]
Shall we delete the branch?

**Pull request closed without merging**
