### PR TITLE
Initial implementation of input devices.

### PR DESCRIPTION
**Pull request by Britefury**

### CODE REVIEW

**Comment by Britefury** [comment]
GTK does indeed :)

This is to be the internal LSpace representation of input device state. :)

**Comment by ptersilie** [comment]
I'm not sure I understand. Why can't we just ask rgtk if the button is pressed. Why do we have to reimplement this?

**Comment by Britefury** [comment]
LSpace constructs a GTK drawing area widget in which our content is rendered. It attaches event handlers to the GTK widget to receive events informing it of mouse motion, button presses, key presses, etc.
LSpace takes these events and sends them to the appropriate element within its element tree; the element that has the caret for key/typing events or the element under the pointer for mouse events, etc. Along with the event it passes the current state of all mouse buttons and the modifier keys, so that the element can use this state to determine how it reacts. These structs represent this state. Otherwise any event handler attached to an LSpace element must ask LSpace for a reference to the appropriate GTK widget, which must then be queried.

**Comment by ltratt** [comment]
I guess one thing I'm confused by is why we're defining our own mouse button states etc. In one sense this decouples us from a particular toolkit, but it's not immediately obvious to me that is a useful thing to do (we're bound to be coupled in many places). So I guess I need a little convincing that we need to define our own model.

**Comment by Britefury** [comment]
Closed due to being bad PR. Will re-open when merging with the input devices branch. Then the purpose will be more plain.

**Pull request closed without merging**
